### ISSUE TITLE
Inconsistent behavior when filtering with category ID instead

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1741] opened 2023-09-18 16:10 UTC
Our database page allows either category ID or name for filtering in the GET parameters, but behaves differently depending on which you use. With [category ID filtering](https://pressfreedomtracker.us/all-incidents/?categories=4) the sidebar filters break and don't reflect the proper category:

<img width="311" alt="image" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/0aac1987-6c95-4e6c-b14b-f5b880e2237b">

and the "chips" at the top of the page show the number 4 instead of a category name:

<img width="233" alt="image" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/03b18c50-5dbb-4f21-bcb7-56547a5649d4">

By contrast using the [category name filtering](https://pressfreedomtracker.us/all-incidents/?categories=Arrest%2FCriminal+Charge) renders everything properly:

<img width="797" alt="image" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/88ca13b7-c1cc-4a76-96e2-afb4e344320e">

I think it's good that we support both options for filtering, but we should normalize the behavior here (especially since we're actively using the ID form in some places as links). Maybe one easy way to future-proof this would be to always provide an HTTP redirect from one form to the other so we only have to design the database page templates and javascript to handle one possibility?

**Comment by chigby** [comment] 2023-09-18 19:22
Just capturing this thought: I think it would be a nice improvement to the back-end code to do some kind of normalizing of strings to IDs (or the other way, if we prefer, but I think I like IDs more).

**Comment by chigby** [comment] 2023-09-18 21:40
Another thought: I think one of the reasons this is happening is that the data used by the database/filter page front end is in CSV format. It's worth remembering that CSV data made available by the API was originally designed to be part of an "export" function -- for people who wanted to download a subset of the Tracker's incident data in a spreadsheet-compatible format, and by design this is _human readable_. Numeric ID fields for categories, journalists, institutions, charge types, etc., were not included in that by design. So, there is inevitably going to be some amount of tension when also using that same data as a basis for various website features where no human is going to be seeing the data directly.

**Comment by dkaoster** [comment] 2023-09-19 05:36
@chigby can you comment on why you like IDs more? I don't have a strong preference but I feel like using the title results in slightly more human-readable urls, but it's not a huge deal to me.

**Comment by chigby** [comment] 2023-09-19 16:22
I guess I don't feel too strongly about this either, and when I think about it, I'm not totally sure the reasons I had in mind are that important:

1. IDs less likely to change. Though names aren't all that likely to change either, and using either names or IDs won't help if the entry is deleted.
2. Numeric IDs make delimiters easier. I actually think there's an active problem on the site right now (though I couldn't find an issue for it) because we're using commas to separate multiple items in the same filter. But this is actually better fixed in different ways than keeping with numeric IDs!
3. I was going to say IDs feel more "real" to me--but I have no idea why I feel that and it's probably not even true! 

So, what it seems like I'm saying here is I'm up for anything.

**Comment by harrislapiroff** [comment] 2023-09-19 16:45
w/r/t "names aren't all that likely to change" we actually have changed names of categories over the tracker's lifetime (physical assault -> assault being at least one instance of this) so that's actually somewhat compelling

**Comment by chigby** [comment] 2023-09-19 18:41
It feels worth reiterating this: if we want to standardize on IDs, we will have to either update the front end to use the JSON API, or update the data that's included in the CSV API (see https://github.com/freedomofpress/pressfreedomtracker.us/issues/1741#issuecomment-1724494720)

**Comment by harrislapiroff** [comment] 2023-09-19 20:14
@chigby Are you sure we have to update either of those? I would like for us to continue _accepting_ either name or ID, but redirect to ID. `fetch` requests automatically resolve redirects by default, so I think we could continue just using the same requests and let them get quietly redirected? Am I missing something that would require changing the structure of requests?

**Comment by harrislapiroff** [comment] 2023-09-19 20:15
(although maybe I should be more wary of the performance implications of an extra HTTP redirect 😅 )

**Comment by harrislapiroff** [comment] 2023-09-19 20:21
Oh—are the filters reading the GET parameters directly? And the same with the yellow chips? So we need the filters to be aware of IDs so they can convert them to human-readable names?

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/c177abc0-3128-46c6-8441-2aae1e141d7f)

Hmmm, I can see that this might get complicated. Maybe you and @dkaoster can hash out the right solution here? My only wariness about switching to the JSON API is that JSON is so much _heavier_ than CSV and I don't want us producing huge page loads for what's one of our most commonly used pages 😅

**Comment by chigby** [comment] 2023-09-19 20:29
Yeah, that's kind of what I'm saying. The filter sidebar is "doing its own filtering" to, for example, produce the bar graph. My recollection is it makes an API request to the backend and then creates the graph by counting the categories -- something it can only do "by text" since that's all the info it has.

Not sure how the chips are produced since I haven't had a chance to read that code, though.

**Comment by harrislapiroff** [comment] 2023-09-20 13:32
One other thing I'll add to think about is what data can be generated in the HTML server side. Obviously anything that needs to be dynamically loaded based on user interaction can't be and any super heavy data sets we may wish to delay until after initial page load. But other stuff we may be able to do that translation from ID to name on the server side instead.

**Comment by chigby** [comment] 2023-09-20 15:24
@harrislapiroff Can you say more about what you mean by "heavier"? As in the JSON format is slower? We have definitely spent a fair amount of time optimizing the DB queries behind CSV format, but I think those same ideas (and probably a lot of the same code) could be applied to the JSON format, it just wasn't something we chose to focus on.

**Comment by chigby** [comment] 2023-09-20 15:33
Beginning to think we may want to want to take more advantage of our `fields` options here: CSV format is fine for both our human-readable exports and our filter sidebar code, but they may need/want to specify different fields, e.g. category ID.

**Comment by harrislapiroff** [comment] 2023-09-20 15:40
@chigby Response-size-wise. JSON has to repeat every header for every entry, unlike CSV, which I expect will make it larger under most circumstances. Here's a real world example. For [this viz](https://observablehq.com/@harrislapiroff/five-years-of-tracking-press-freedom) I make a request to
`https://pressfreedomtracker.us/api/edge/incidents/?format=csv&limit=99999&fields=date,title,url,categories` which is **382.6KB**. Swapping that out for `https://pressfreedomtracker.us/api/edge/incidents/?format=json&limit=99999&fields=date,title,url,categories` makes it **460.3KB**, 20% larger. I expect the difference to be even larger with more fields included. I tend to prefer CSV data when working on data visualizations for this reason.

If you're not sure this is a significant difference for our use cases, feel free to play with it and let me know what you discover.

**Comment by dkaoster** [comment] 2023-09-20 15:44
I'm wondering if it would be a good idea to have a separate endpoint just for the category data, such as mapping the categories between their IDs, titles, and "slug" (the key we use for the little icons). That way it's not repeated in the data making the csv / json files bigger and perhaps we can even have that just baked into the html as @harrislapiroff mentioned?

**Comment by harrislapiroff** [comment] 2023-09-20 15:46
We have a category endpoint just for that! But yeah, I'd maybe even bake that into the HTML and save a request since it's small and won't change between page loads.

**Comment by chigby** [comment] 2023-09-20 16:22
I have an idea for this, let me give it a try and see what you all think.

**Comment by chigby** [comment] 2023-09-20 16:53
https://github.com/freedomofpress/pressfreedomtracker.us/pull/1746

**Comment by chigby** [comment] 2023-09-20 16:54
It turns out we already kind of have a category id to title mapping in our serialized filter definitions.

**Comment by harrislapiroff** [comment] 2023-09-20 17:45
@chigby Am I correct that even with #1746 merged, we'll still need a fix for the yellow chips? Or do those pull from the filter code? I would actually maybe favor those chips being fully server-side generated—though perhaps that's unwise if we're eventually going to implement some sort of dynamic loading. But they should be more aware of what's a filter and what isn't and also to be able to use human readable names, not ids, for *all* objects (including tags and other m2m fields) and I suspect the easiest/most consistent way to achieve that would be for them to be generated server side.

**Comment by chigby** [comment] 2023-09-20 17:57
Correct, that PR does not address the yellow chips

**Closed as completed** 2023-09-25 14:49 UTC
