### ISSUE TITLE
New York not showing up in bubble map

### ISSUE THREAD

**Issue by stephaniesugars** [freedomofpress/pressfreedomtracker.us#1902] opened 2024-11-14 20:33 UTC
When doing a bubble map "New York, New York" does not appear as a viable option for grouping by city. I ran into this issue last year as well -- it appears that whatever system we're using has "New York City, New York" instead, which goes against our style. Any way we can change this? For reference, here's the same bubble map, but with city vs. state grouping:
![2024 arrests - city grouping](https://github.com/user-attachments/assets/d00fe793-4524-4d52-8660-429e54ae4314)
![2024 arrests - state grouping](https://github.com/user-attachments/assets/cdc6f801-8652-42d3-b32b-8624df5e64ac)

**Comment by stephaniesugars** [comment] 2024-12-02 21:14
We're going to be publishing our annual arrest report on Dec. 12, though we can push that slightly if necessary. As nearly half of the arrests were in NYC this year, we're really hoping to be able to have the bubble map display by city. Any idea whether this is going to be addressed before then? If not, let me know so I can pivot.

**Comment by stephaniesugars** [comment] 2024-12-02 21:15
Also, not sure why, but the Florida cases aren't showing up when it's grouped by state, no clue why that's happening.

**Comment by harrislapiroff** [comment] 2024-12-05 19:01
Closing as a duplicate of #1797. We're working on it now! :D

**Closed as completed by harrislapiroff** 2024-12-05 19:01 UTC
